name: lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2

      - name: Run Shellcheck
        uses: azohra/shell-linter@latest
        with:
          path: "dotenv.sh,scripts/install.sh"
